# Generated by Django 5.1.1 on 2024-09-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0011_alter_seance_unique_together_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='licence',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.group'),
            preserve_default=False,
        ),
    ]
