# Generated by Django 5.1.1 on 2024-09-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0003_department_slug'),
        ('account', '0002_alter_etudiant_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.semestre'),
        ),
    ]
