# Generated by Django 5.1.1 on 2024-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_etudiant_departement_alter_etudiant_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='pv',
            field=models.CharField(default=23, max_length=150),
            preserve_default=False,
        ),
    ]
