# Generated by Django 5.1.1 on 2024-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_etudiant_pv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='departement',
        ),
    ]
