# Generated by Django 5.1.1 on 2024-10-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_etudiant_photo_etudiant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(default='conakry', max_length=100),
            preserve_default=False,
        ),
    ]
