# Generated by Django 5.1.1 on 2024-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_etudiant_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='pv',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_profils'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
