# Generated by Django 5.1.1 on 2024-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_etudiant_pv_alter_etudiant_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_profils'),
        ),
    ]
