# Generated by Django 5.0.6 on 2024-09-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmploiApp', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.department'),
        ),
        migrations.AddField(
            model_name='profdispoweek',
            name='hourRange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.hourrange'),
        ),
        migrations.AddField(
            model_name='profdispoweek',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AddField(
            model_name='seance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.classroom'),
        ),
        migrations.AddField(
            model_name='seance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.course'),
        ),
        migrations.AddField(
            model_name='seance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.semestre'),
        ),
    ]
