# Generated by Django 5.1.1 on 2024-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='zoeu', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
