# Generated by Django 5.1.1 on 2024-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourrange',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hourrange',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
