# Generated by Django 5.1.1 on 2024-09-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0003_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.semestre'),
            preserve_default=False,
        ),
    ]
