# Generated by Django 5.1.1 on 2024-09-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0004_alter_licence_options_alter_licence_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='ProfDispoWeek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.profdispoweek', verbose_name='Disponiblité du prof'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('number', 'licence')},
        ),
    ]
