# Generated by Django 5.1.1 on 2024-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0006_rename_profdispoweek_seance_profdispoweek'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('group', 'course', 'profDispoWeek')},
        ),
        migrations.AddField(
            model_name='profdispoweek',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='seance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='start_time',
        ),
    ]
