# Generated by Django 5.1.1 on 2024-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0007_alter_seance_unique_together_profdispoweek_busy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
