# Generated by Django 5.1.1 on 2024-09-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0008_seance_end_time_seance_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
