# Generated by Django 5.1.1 on 2024-09-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0009_alter_seance_end_time_alter_seance_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourrange',
            options={'ordering': ['day_week']},
        ),
        migrations.AlterModelOptions(
            name='profdispoweek',
            options={'ordering': ['hourRange__day_week']},
        ),
        migrations.RemoveField(
            model_name='seance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='start_time',
        ),
    ]
