# Generated by Django 5.1.1 on 2024-09-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0010_alter_hourrange_options_alter_profdispoweek_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='profDispoWeek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmploiApp.profdispoweek', verbose_name='Disponibilité du prof'),
        ),
    ]
