# Generated by Django 5.1.1 on 2024-09-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0011_alter_seance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='h_end',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seance',
            name='h_start',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
