# Generated by Django 5.1.1 on 2024-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0013_seance_day_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profdispoweek',
            name='hourRange',
        ),
        migrations.AlterModelOptions(
            name='profdispoweek',
            options={'ordering': ['day_week']},
        ),
        migrations.AddField(
            model_name='profdispoweek',
            name='day_week',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profdispoweek',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profdispoweek',
            name='start_time',
            field=models.TimeField(default='01:00:00'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HourRange',
        ),
    ]
