# Generated by Django 5.1.1 on 2024-10-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0016_alter_group_licence_remove_seance_group_seance_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
