# Generated by Django 5.1.1 on 2024-10-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0020_alter_course_teacher'),
        ('account', '0005_alter_etudiant_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
    ]
