# Generated by Django 5.1.1 on 2024-10-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0021_alter_course_teacher'),
        ('account', '0005_alter_etudiant_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
            preserve_default=False,
        ),
    ]
