# Generated by Django 5.1.1 on 2024-10-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0022_seance_professeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
