# Generated by Django 5.1.1 on 2024-10-15 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0023_remove_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='EmploiApp.classroom'),
        ),
    ]
