# Generated by Django 5.1.1 on 2024-10-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0024_alter_seance_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='EmploiApp.group'),
        ),
    ]
