# Generated by Django 5.1.1 on 2024-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0025_alter_seance_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='group',
            field=models.ManyToManyField(to='EmploiApp.group'),
        ),
    ]
