# Generated by Django 5.1.1 on 2024-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0026_alter_seance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.CharField(default='labo', max_length=20),
            preserve_default=False,
        ),
    ]
