# Generated by Django 5.1.2 on 2024-10-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmploiApp', '0027_classroom_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('M', 'Magistral'), ('TP', 'Travaux Pratiques')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Durée totale du cours en heures'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
